- hosts: raspberrypi
  remote_user: pi
  tasks:
# make sure python and libraries are installed
  - name: deploy code
    copy: src=../../app/ dest=/home/pi/lcdsysinfo/app mode=0755
  - name: Python package
    become: yes
    become_user: root
    pip: requirements=/home/pi/lcdsysinfo/app/requirements.txt
# /pylcdsysinfo
  - name: permissions for USB
    become: yes
    become_user: root
    copy: src=../../99-lcdsysinfo.rules dest=/etc/udev/rules.d/
  - name: Test the command
    command: chdir=/home/pi/lcdsysinfo/app ./weather.sh
  - name: install cron job
    cron: name="run display" minute="*/5" job="cd /home/pi/lcdsysinfo/app/; ./weather.sh | /usr/bin/logger -t lcdsys"
 
