- hosts: raspberrypi
  remote_user: pi
  tasks:
# make sure python and libraries are installed
  - name: deploy code
    copy: src=../../app/ dest=/home/pi/lcdsysinfo/app
  - name: Test the command
    command: chdir=/home/pi/lcdsysinfo /bin/sh app/weather.sh
# install cron job, run the command
