- hosts: raspberrypi
  remote_user: pi
  tasks:
# make sure python and libraries are installed
  - name: Python package
    pip: name=pyusb
# /pylcdsysinfo
  - name: deploy code
    copy: src=../../app/ dest=/home/pi/lcdsysinfo/app
  - name: permissions for USB
    become: yes
    become_user: root
    copy: src=../../99-lcdsysinfo.rules dest=/etc/udev/rules.d/
  - name: Test the command
    command: chdir=/home/pi/lcdsysinfo /bin/sh app/weather.sh
  - name: install cron job
    cron: name="run display" minute="*" job="(cd /home/pi/lcdsysinfo/app/; ./weather.sh >/dev/null)"
 
